### PR TITLE
Added ISO9660 test file and tests

### LINKED ISSUE #689: Add ISO9660 support
Create an ISO9660 sample file (from dfirlabs) and add to test_data.
Add tests to relevant TSK based classes (tsk_file_entry, tsk_file_io, etc).

### PR DESCRIPTION
**Pull request by sydp**
This PR updates tsk_file_entry.py to support creation timestamps for ISO9660 files and adds associated tests.

The test file was generated using the dfirlabs iso9660-specimens script.

Fixes #689

### CODE REVIEW

**Comment by joachimmetz** [comment]
@sydp thx, could you use the https://github.com/log2timeline/dfvfs/blob/main/utils/generate_test_data_linux.sh script to generate test data with the same content as the other test files?

**Comment by joachimmetz** [comment]
Please update https://github.com/log2timeline/dfvfs/blob/main/docs/sources/Supported-formats.md as well with the supported IS9660 variants (levels)

**Comment by joachimmetz** [comment]
@sydp made some changes, PTAL and let me know if you think this PR is finalized.

**Comment by sydp** [comment]
> @sydp made some changes, PTAL and let me know if you think this PR is finalized.

Thanks, the changes LGTM.

**Review by joachimmetz — APPROVED** [review]
LGTM

**Pull request merged**
