### PR TITLE
Added APFS volume system support

### PR DESCRIPTION
**Pull request by joachimmetz**
Added APFS volume system support

### CODE REVIEW

**Comment by Onager** [comment]
Appveyor and MacOS tests are failing with: 

```
======================================================================
FAIL: testIterateVolumes (volume.apfs_volume_system.APFSVolumeSystemTest)
Test the iterate volumes functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\dfvfs\tests\volume\apfs_volume_system.py", line 62, in testIterateVolumes
    self.assertEqual(volume_attribute.value, expected_value)
AssertionError: u'57f3b544-b3e9-3d48-893c-3802306b5132' != u'44b5f357-e9b3-483d-893c-3802306b5132'
- 57f3b544-b3e9-3d48-893c-3802306b5132
+ 44b5f357-e9b3-483d-893c-3802306b5132
```
Looks like an endianess issue, so probably an issue in libapfs

**Comment by joachimmetz** [comment]
Undid additional changes for consistency sake. Either make this change across all code or not.

**Comment by joachimmetz** [comment]
> Looks like an endianess issue, so probably an issue in libapfs

This is due to an issue in the Python-bindings and has already been fixed.

**Comment by Onager** [comment]
Re-triggered appveyor and travis tests

**Comment by Onager** [comment]
Per discussion, please feel free to merge this when the tests are passing, and I'll do another PR with other changes.

**Pull request merged**
